---
title: "p8105_hw1_cn2604"
output: github_document
date: "2022-09-17"
---

# Problem 1

```{r loading_library, echo=FALSE, message=FALSE}
library(knitr)
library(tidyverse)
data("penguins", package = "palmerpenguins")
penguins_table = kable(penguins)
```
The __penguins__ dataset has `r nrow(penguins)` rows and `r ncol(penguins)` columns.
The flipper length is `r round(mean(penguins$flipper_length_mm, na.rm=TRUE), digits = 2)`mm.
<!-- The appearance of __penguins__ dataset is `r penguins_table` -->

```{r scatterplot}
attach(penguins)
ggplot(data = penguins, 
       mapping = aes(x = bill_length_mm, 
                     y = flipper_length_mm,
                 color = species)) +
  geom_point(na.rm = TRUE)
ggsave("scatterplot.pdf")
```
# Problem 2
```{r dataframe}
dataframe = tibble(
  var_norm = rnorm(n=10),
  var_logical = var_norm > 0,
  var_char = letters[1:10],
  var_factor = factor(sample(x = c("one","two","three"), 
                             size = 10,
                             replace = TRUE)
  )
)
```
```{r dataframe_calculation, eval=FALSE}
  mean_norm = mean(pull(dataframe, var_norm))
  mean_logical = mean(as.numeric(pull(dataframe, var_logical)))
  mean_char = mean(as.numeric(pull(dataframe, var_char)))
  mean_factor = mean(as.numeric(pull(dataframe, var_factor)))
```
The results show that as.numeric function does not work for _var_char_, but work for _var_logical_ and _var_factor_. 

